version: "3.9"

services:
  db:
    image: postgres:12.7
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: >
      sh -c "python3.9 manage.py migrate "
    volumes:
      - .:/code
      - /tmp:/tmp
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.2
    hostname: redis_db
    restart: always
    depends_on:
      - db

  celery:
    build: .
    restart: always
    volumes:
      - .:/code
    command: celery -A config worker -l info
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    restart: always
    volumes:
      - .:/code
    command: celery -A config beat -l info
    depends_on:
      - db
      - redis
